//productos disponibles 
const productos = [
  {
    codigo: 1,
    nombre: "Palo con medidas",
    descripcion: "",
    precio: 15000,
    imagen: "images/productos/palo.jpg",
    stock: 5,
  },
  {
    codigo: 2,
    nombre: "Cortantes",
    descripcion: "",
    precio: 6000,
    imagen: "images/productos/cortantes.png",
    stock: 5,
  },
  {
    codigo: 3,
    nombre: "Mangas X4",
    descripcion: "",
    precio: 5000,
    imagen: "images/productos/manga2.png",
    stock: 5,
  },
  {
    codigo: 4,
    nombre: "Palo de amasar",
    descripcion: "",
    precio: 10000,
    imagen: "images/productos/palo2.jpg",
    stock: 5,
  },
  {
    codigo: 5,
    nombre: "Budinera",
    descripcion: "",
    precio: 9000,
    imagen: "images/productos/budinera.jpg",
    stock: 5,
  },
  {
    codigo: 6,
    nombre: "Espátula",
    descripcion: "",
    precio: 5500,
    imagen: "images/productos/espatula.jpg",
    stock: 5,
  },
  {
    codigo: 7,
    nombre: "Taza medidora",
    descripcion: "",
    precio: 11000,
    imagen: "images/productos/tazaMedidas.jpg",
    stock: 5,
  },
  {
    codigo: 8,
    nombre: "Set de moldes X3",
    descripcion: "",
    precio: 15000,
    imagen: "images/productos/moldeX3.jpg",
    stock: 5,
  },
  {
    codigo: 9,
    nombre: "Molde desmontable",
    descripcion: "",
    precio: 18000,
    imagen: "images/productos/moldeDesmontable.jpg",
    stock: 5,
  },
  {
    codigo: 10,
    nombre: "Molde corazón",
    descripcion: "",
    precio: 17000,
    imagen: "images/productos/moldeCorazon.jpg",
    stock: 5,
  },
  {
    codigo: 11,
    nombre: "Set de mini moldes",
    descripcion: "",
    precio: 12000,
    imagen: "images/productos/moldesMini.png",
    stock: 5,
  },
  {
    codigo: 12,
    nombre: "Molde tarta",
    descripcion: "",
    precio: 13500,
    imagen: "images/productos/moldeTartaDesmontable.jpg",
    stock: 5,
  },
  {
    codigo: 13,
    nombre: "Molde para muffins",
    descripcion: "",
    precio: 13500,
    imagen: "images/productos/muffinera.jpg",
    stock: 5,
  },
  {
    codigo: 14,
    nombre: "Soplete",
    descripcion: "",
    precio: 20500,
    imagen: "images/productos/soplete.jpg",
    stock: 5,
  },
  {
    codigo: 15,
    nombre: "Molde bombones",
    descripcion: "",
    precio: 11200,
    imagen: "images/productos/moldechoco.jpg",
    stock: 5,
  },
  {
    codigo: 16,
    nombre: "Plato giratorio",
    descripcion: "",
    precio: 25000,
    imagen: "images/productos/platogiratorio.jpg",
    stock: 5,
  },
  {
    codigo: 17,
    nombre: "Base para tartas",
    descripcion: "",
    precio: 85000,
    imagen: "images/productos/basetarta.jpg",
    stock: 5,
  },
  {
    codigo: 18,
    nombre: "Pirotines X10",
    descripcion: "",
    precio: 2000,
    imagen: "images/productos/pirotines.jpg",
    stock: 5,
  },
];


